const express = require('express');
const router = express.Router();
const pool = require('../db');
const { verifyToken } = require('../middleware/auth');
router.use(verifyToken);
router.get('/', async (req, res) => { try { res.json((await pool.query('SELECT * FROM clients ORDER BY onboarded_at DESC NULLS LAST')).rows); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/:id', async (req, res) => { try { const r = await pool.query('SELECT * FROM clients WHERE id=$1',[req.params.id]); if(!r.rows.length) return res.status(404).json({error:'Not found'}); res.json(r.rows[0]); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/', async (req, res) => { try { const {name,company,email,industry,tier,status,onboarded_at,total_tasks,satisfaction_score}=req.body; const r=await pool.query('INSERT INTO clients (name,company,email,industry,tier,status,onboarded_at,total_tasks,satisfaction_score) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[name,company,email,industry,tier||'standard',status||'active',onboarded_at,total_tasks||0,satisfaction_score]); res.status(201).json(r.rows[0]); } catch (err) { res.status(500).json({ error: err.message }); } });
router.put('/:id', async (req, res) => { try { const {name,company,email,industry,tier,status,onboarded_at,total_tasks,satisfaction_score}=req.body; const r=await pool.query('UPDATE clients SET name=$1,company=$2,email=$3,industry=$4,tier=$5,status=$6,onboarded_at=$7,total_tasks=$8,satisfaction_score=$9 WHERE id=$10 RETURNING *',[name,company,email,industry,tier,status,onboarded_at,total_tasks,satisfaction_score,req.params.id]); if(!r.rows.length) return res.status(404).json({error:'Not found'}); res.json(r.rows[0]); } catch (err) { res.status(500).json({ error: err.message }); } });
router.delete('/:id', async (req, res) => { try { await pool.query('DELETE FROM clients WHERE id=$1',[req.params.id]); res.json({success:true}); } catch (err) { res.status(500).json({ error: err.message }); } });
module.exports = router;
