const express = require('express');
const cors = require('cors');
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', require('./routes/auth'));
app.use('/api/clients', require('./routes/clients'));
app.use('/api/tasks', require('./routes/tasks'));
app.use('/api/staff', require('./routes/staff'));
app.use('/api/invoices', require('./routes/invoices'));
app.use('/api/slas', require('./routes/slas'));
app.use('/api/templates', require('./routes/templates'));
app.use('/api/ai', require('./routes/ai'));
app.use('/api', require('./routes/features'));
app.use('/api/admin', require('./routes/sample_data'));
app.use('/api/dashboard', require('./routes/dashboard'));
app.use('/api/gap-ai-template-recommendation', require('./routes/gap-ai-template-recommendation'));
app.use('/api/gap-ai-pricing-optimizer', require('./routes/gap-ai-pricing-optimizer'));
app.use('/api/gap-ai-capacity-forecast', require('./routes/gap-ai-capacity-forecast'));
app.use('/api/gap-ai-deliverable-generator', require('./routes/gap-ai-deliverable-generator'));
app.use('/api/gap-ai-client-churn-predictor', require('./routes/gap-ai-client-churn-predictor'));
app.use('/api/gap-nonai-time-tracking', require('./routes/gap-nonai-time-tracking'));
app.use('/api/gap-nonai-client-portal', require('./routes/gap-nonai-client-portal'));
app.use('/api/gap-nonai-deliverable-storage', require('./routes/gap-nonai-deliverable-storage'));
app.use('/api/gap-nonai-payment-gateway', require('./routes/gap-nonai-payment-gateway'));
app.use('/api/gap-nonai-notification-layer', require('./routes/gap-nonai-notification-layer'));
app.use('/api/cf-agent-fleet', require('./routes/cf-agent-fleet'));
app.use('/api/cf-outcome-pricing', require('./routes/cf-outcome-pricing'));
app.use('/api/cf-slack-channel-auto', require('./routes/cf-slack-channel-auto'));
app.use('/api/cf-margin-analyzer', require('./routes/cf-margin-analyzer'));
app.use('/api/cf-service-productize', require('./routes/cf-service-productize'));
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ error: 'Internal server error' }); });
const PORT = process.env.PORT || 3003;
app.listen(PORT, () => console.log(`ServiceFlow backend running on port ${PORT}`));
